apiVersion: v1
kind: Service
metadata:
  name: { { include "mission-control-ai-assistant-proxy.fullname" . } }
  labels: { { - include "mission-control-ai-assistant-proxy.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  selector:
    app.kubernetes.io/name: { { include "mission-control-ai-assistant-proxy.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
  ports:
    - name: http
      port: { { .Values.config.httpPort } }
      targetPort: http
    - name: ws
      port: { { .Values.config.wsPort } }
      targetPort: ws
